version: '3.4'

services:
  api:
    image: itbit-asp-net-core
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:80"
    depends_on: 
      - migrations
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"    
      CHECK_POLICY: "OFF"
      CHECK_EXPIRATION: "OFF"
      MSSQL_SA_PASSWORD: "Password@12345"
    ports:
    - "1433:1433"
    depends_on: 
      - migrations
  migrations:
    build: 
      context: .
      dockerfile: Migrations.Dockerfile